# Main Profile
info:
  app:
    name: 'connectly'
    version: '0.0.1'

spring:
  application:
    name: connectly



  session:
    store-type: redis

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  output:
    ansi:
      enabled: always

  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'

  thymeleaf:
    cache: true
    suffix: .html

  redis:
    host: localhost
    port: 6379

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: WARN

  com:
    connectly:
      connectly:
        config: INFO

  org:
    springframework:
      security: TRACE
      data:
        repository:
          config:
            RepositoryConfigurationExtensionSupport: WARN


  pattern:
    console: "[%clr(%level){highlight}] %d{yyyy-MM-dd HH:mm:ss} -- [%clr(%thread){yellow}] [%logger{36}] :: %clr(%msg){blue} %n"
