# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  sql:
    init:
      platform: postgresql
      mode: always
      data-locations: classpath:db/data-postgresql.sql

  jpa:
    hibernate:
      ddl-auto: create-drop # create-drop || update
    show-sql: true


  thymeleaf:
    cache: false

logging:
  level:
    root: INFO

  org:
    hibernate:
      SQL: INFO

  com:
    connectly:
      connectly:
        config: INFO
