# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  thymeleaf:
    cache: true # Enable cache for production

  redis:
    host: production-redis-host
    port: 6379

logging:
  level:
    root: WARN # Less verbose logging for production

  com:
    connectly:
      connectly:
        config: WARN



