info:
  app:
    name: 'connectly'
    version: '0.0.1'

spring:
  application:
    name: connectly

  main:
    banner-mode: 'off'

  # Thymeleaf configuration
  thymeleaf:
    cache: true # Enable/disable template caching (useful for production)
    suffix: .html # Suffix for template files

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: WARN
