# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  thymeleaf:
    cache: true

logging:
  level:
    root: WARN

  com:
    connectly:
      connectly:
        config: WARN



