# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/connectlydb?createDatabaseIfNotExist=true
    username: connectly_app_user
    password: PqNmVSh08Tw5ZoszaaW4jxJ5arPgr2zYD3bxOpohDYLkKa1vjY
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create-drop # update
      database: postgresql
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false # Disable cache for development to see template changes immediately

  redis:
    host: localhost
    port: 6379

logging:
  level:
    root: INFO

  org:
    hibernate:
      SQL: INFO

  com:
    connectly:
      connectly:
        config: INFO


