# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  sql:
    init:
      platform: postgresql
      mode: always
      continue-on-error: true
      data-locations: optional:classpath*:db/data-postgresql.sql

  jpa:
    hibernate:
      ddl-auto: update # create-drop || update
    #show-sql: true
    properties:
      hibernate.format_sql: true


  thymeleaf:
    cache: false

logging:
  level:
    root: INFO

  org:
    hibernate:
      SQL: INFO

  com:
    connectly:
      connectly:
        config: INFO
