# Main Profile
info:
  app:
    name: 'connectly'
    version: '0.0.1'

spring:
  application:
    name: connectly

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always


  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update
        database: postgresql
        jdbc:
          time_zone: UTC

  output:
    ansi:
      enabled: always

  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'

  thymeleaf:
    cache: true
    suffix: .html

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    root: WARN

  com:
    connectly:
      connectly:
        config: WARN

  org:
    springframework:
      security: TRACE
      data:
        repository:
          config:
            RepositoryConfigurationExtensionSupport: WARN


  pattern:
    console: "[%clr(%level){highlight}] %d{yyyy-MM-dd HH:mm:ss} -- [%clr(%thread){yellow}] [%logger{36}] :: %clr(%msg){blue} %n"
